version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
  restful-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./restful-api
    volumes:
      - /app/node_modules
      - ./restful-api:/app
  portal:
    build:
      dockerfile: Dockerfile.dev
      context: ./portal
    volumes:
      - /app/node_modules
      - ./portal:/app
  sat:
    build:
      dockerfile: dockerfile-assetdaemon.docdev
      context: ./native
    volumes:
      - ./native:/app
