FROM pomeranian/builder:9.2.0 as builder
WORKDIR /app
ARG LIBNAME_NAME

# core libs (3rd party)
COPY --from=pomeranian/restbed              /build/.                    /usr/local/
COPY --from=sixthview/rapidjson-package     /build/rapidjson/.          /usr/local/
COPY --from=sixthview/stb-package           /build/stb/.                /usr/local/
COPY --from=sixthview/boost-package         /build/boost/.              /usr/local/
COPY --from=sixthview/websocketpp-package   /build/websocketpp/.        /usr/local/
COPY --from=pomeranian/libzip               /build/.                    /usr/local/

# database libs (3rd party)
COPY --from=pomeranian/mongo-c-driver       /build/.                    /usr/local/
COPY --from=pomeranian/mongo-cxx-driver     /build/.                    /usr/local/

COPY . .

RUN echo "cmake_minimum_required (VERSION 2.6)\ninclude(../CMakeLists.txt NO_POLICY_SCOPE)\nbuild_core_lib( $LIBNAME_NAME )" > ./$LIBNAME_NAME/CMakeLists.txt

RUN mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/build ../$LIBNAME_NAME && make -j8 && make install && make clean

FROM alpine
COPY --from=builder /build /build
