FROM gcc:latest
RUN apt-get update && apt-get install -y cmake
ARG LIBNAME_NAME
ARG LIBNAME_VERSION
ARG GITUSER
ARG OPTIONS

WORKDIR /builder/$LIBNAME_NAME
RUN git clone --recursive --branch=$LIBNAME_VERSION https://github.com/$GITUSER/$LIBNAME_NAME.git
RUN cmake $OPTIONS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/build/$LIBNAME_NAME $LIBNAME_NAME
RUN make -j8
RUN make install
RUN make clean
WORKDIR /build
RUN rm -rf /builder

