FROM pomeranian/builder:9.2.0 as builder

ARG LIB_NAME

# core libs (3rd party)
COPY --from=pomeranian/restbed              /build/.                    /usr/local/
COPY --from=pomeranian/rapidjson            /build/.                    /usr/local/
COPY --from=pomeranian/stb                  /build/.                    /usr/local/
COPY --from=pomeranian/boost                /build/.                    /usr/local/
COPY --from=pomeranian/websocketpp          /build/.                    /usr/local/
COPY --from=pomeranian/libzip               /build/.                    /usr/local/

# database libs (3rd party)
COPY --from=pomeranian/mongo-c-driver       /build/.                    /usr/local/
COPY --from=pomeranian/mongo-cxx-driver     /build/.                    /usr/local/

COPY . .

RUN cd $LIB_NAME && echo "cmake_minimum_required (VERSION 2.6)\ninclude(../CMakeLists.txt NO_POLICY_SCOPE)\nbuild_core_lib( $LIB_NAME )" > CMakeLists.txt

RUN mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/build -DBUILD_FOR_LIB=TRUE -DBUILD_FROM_SOURCE=TRUE ../${LIB_NAME} && make -j8 && make install && make clean

FROM alpine
COPY --from=builder /build /build
