FROM nginx
COPY ./http-standalone.conf /etc/nginx/conf.d/http.conf
COPY ./stream-standalone.conf /etc/nginx/conf.d/stream.conf
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./localhost.pem /etc/nginx/
COPY ./localhost-key.pem /etc/nginx/
COPY ./ca.crt /etc/nginx/client_certs/ca.crt

EXPOSE 80
EXPOSE 443
