export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const WASM_LOAD_START = "WASM_LOAD_START";
export const WASM_LOAD_SUCCESS = "WASM_LOAD_SUCCESS";
export const WASM_LOAD_FAILED = "WASM_LOAD_FAILED";
export const WASM_RUN_SUCCESS = "WASM_RUN_SUCCESS";
export const WASM_RUN_FAILED = "WASM_RUN_FAILED";
