name: nginx (Build,Test,Deploy)

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_ID }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        context: ./nginx
        image_name: ${{ secrets.DOCKER_HUB_ID }}/nginx