name: Build, Test and Deploy all

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SECRET_PRIVATE_DEPLOY_KEY }}
    
    - name: Build all core libs
      run: |
        ./build_native_lib.sh ${{ secrets.DOCKER_HUB_ID }} core
        ./build_native_lib.sh ${{ secrets.DOCKER_HUB_ID }} database
    - name: Build asset_daemon
      run: |
        ./build_native_tool.sh ${{ secrets.DOCKER_HUB_ID }} asset_daemon
    - name: Build NGINX
      run: docker build -t ${{ secrets.DOCKER_HUB_ID }}/nginx ./nginx      
    - name: Build restful-api
      run: docker build -t ${{ secrets.DOCKER_HUB_ID }}/restful-api ./restful-api
    - name: Build rsinitiate
      run: docker build -t ${{ secrets.DOCKER_HUB_ID }}/mongo-rsinitiate ./mongo

    - name: Docker hub login
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_ID }} --password-stdin
              
    - name: Docker Push all core-libs
      run: |
        ./publish_native_lib.sh ${{ secrets.DOCKER_HUB_ID }} core
        ./publish_native_lib.sh ${{ secrets.DOCKER_HUB_ID }} database
    - name: Docker Push asset_daemon
      run: |
        docker push ${{ secrets.DOCKER_HUB_ID }}/asset_daemon
    - name: Docker Push NGINX
      run: docker push ${{ secrets.DOCKER_HUB_ID }}/nginx
    - name: Docker Push restful-api
      run: docker push ${{ secrets.DOCKER_HUB_ID }}/restful-api
    - name: Docker Push rsinitiate
      run: docker push ${{ secrets.DOCKER_HUB_ID }}/mongo-rsinitiate
