name: Build and Deploy

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Copy deploy script via scp.
      run: scp ${{ github.workspace }}/docker-compose.yml ${{ secrets.DROPLET_USER}}@${{ secrets.DROPLET_IP }}:/root
    - name: Deploy. (Signal cloud hosting via SSH to put new dockers live)
      run: ssh -oStrictHostKeyChecking=no -v ${{ secrets.DROPLET_USER}}@${{ secrets.DROPLET_IP }} 'docker-compose up -d --build'

    - name: Docker hub login
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_ID }} --password-stdin
        
    - name: Build NGINX
      run: docker build -t ateventhorizon/49view-nginx ./nginx      
    - name: Build restful-api
      run: docker build -t ateventhorizon/49view-restful-api ./restful-api
    - name: Build portal
      run: docker build -t ateventhorizon/49view-portal ./portal
    - name: Build rsinitiate
      run: docker build -t ateventhorizon/49view-mongo-rsinitiate ./mongo
      
    - name: Docker Push NGINX
      run: docker push ateventhorizon/49view-nginx
    - name: Docker Push restful-api
      run: docker push ateventhorizon/49view-restful-api
    - name: Docker Push portal
      run: docker push ateventhorizon/49view-portal
    - name: Docker Push rsinitiate
      run: docker push ateventhorizon/49view-mongo-rsinitiate

